[package]
name = "wacc"
description = "writing a c compiler"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "wacc"
path = "src/driver.rs"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
