[workspace.metadata.crane]
name = "wacc"

[workspace.package]
description = "writing a c compiler"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace]
resolver = "2"
members = ["crates/*"]
